transparency-dev/armored-witness-os

trusted_os/rpc.go, trusted_os/rpmb.go
This RPC API allows the Trusted Applet to use its own protected sector for arbitrary authenticated data read/write as well as retrieving the RPMB monotonic counter.
=> add RPC API for TA RPMB own sector use

trusted_os/load.go, trusted_os/main.go
This PR makes the hardware unique key derivation, for TA own use, tied to the public key as diversifier opposed to the TA ELF hash. This allows key reuse through different TA versions.
=> use applet public key as key derivation diversifier

Makefile, trusted_os/bee.go, trusted_os/dma.go, trusted_os/load.go, trusted_os/mem_bee.go
This commit supports [amored-witness-boot PR #12](https://github.com/transparency-dev/armored-witness-boot/pull/12) by adding optional compile time flags to support BEE aliased regions.
=> support BEE relocation

trusted_os/console.go, trusted_os/debug.go, trusted_os/load.go, trusted_os/log.go
This PR adds logging of `file:line` (only when compiled with `DEBUG=1`) when the Trusted Applet exits ungracefully (e.g. data abort).
=> debug TA file:line on fatal exceptions

trusted_os/handler.go
This helps ensure that it doesn't get starved and spuriously reboot the device.
=> Service WD with every interrupt

go.mod, go.sum, trusted_os/load.go
The Watchdog's `EnableInterrupt` call now takes a parameter specifying how much "notice" to give when generating a service request interrupt before the watchdog itself will trigger.
=> Update to match Watchdog API

cmd/witnessctl/api.go
When issuing USB control commands to the api.U2FHID_ARMORY_INF mapping right before issuing one to the api.U2FHID_ARMORY_CFG mapping the following happens.
```
panic: runtime error: index out of range [2] with length 1
goroutine 33 [running]:
github.com/gsora/fidati/u2fhid.(*Handler).Tx(0x82818650, {0x0, 0x0, 0x0}, {0x0, 0x0})
github.com/gsora/fidati@v0.0.0-20220824075547-eeb0a5f7d6c3/u2fhid/handler.go:38 +0x690
github.com/usbarmory/tamago/soc/nxp/usb.(*endpoint).tx(0x82830660)
github.com/usbarmory/tamago@v0.0.0-20230724190245-6f2dec2f8412/soc/nxp/usb/endpoint_handler.go:44 +0x48
```
As a workaround while this issue is solved this PR avoids issuing status (which is done solely for the reason of printing out the target serial number) before CFG or OTA commands.
=> workaround fidati pkg bug on consecutive commands

trusted_os/rpc.go
This PR allows key derivation under emulation, to avoid potential security issues with emulation detection (which feels anyway [safe](https://github.com/usbarmory/tamago/blob/42b6e427753aa24d3e9138a9c8b6899692a1811e/soc/nxp/imx6ul/init.go#L67)) this is only allowed when compiled in debug mode.
=> set an empty derived key under emulation 

trusted_os/flash.go, trusted_os/main.go, trusted_os/rpc.go, trusted_os/rpmb.go, trusted_os/storage.go, trusted_os/storage_debug.go
This change causes `DEBUG=1` OS builds to compile-in a "fake" RAM-based storage which is used in place of MMC flash when not running on native h/w. Since this happens as the OS level, it's completely transparent to the applet.
This allows us to run the OS+applet under `qemu` (which has no emulation of the MMC device) without needing to manually modify storage code _in the applet_, making debugging easier.
=> Use fake storage when running on qemu in DEBUG=1 mode

api/rpc/rpc.go, go.mod, go.sum, trusted_os/rpc.go
Adds the outline of an RPC implementation of the applet's `UpdateLocal` interface.
=> Add Update related RPC stubs

go.mod, go.sum, trusted_os/handler.go
Requires a minor change to follow the `GetInterrupt` API.
=> Bump tamago to 64264ab

Makefile, README.md
This PR ensures that debugging symbols are kept on the ELF compiled for qemu + GDB execution.
=> Keep symbols on qemu-gdb target

.github/workflows/pr_build.yml, Makefile, go.mod, go.sum
Adds support for logging firmware artefacts to a local FT log for development purposes.
Analogous to transparency-dev/armored-witness-applet/pull/114 .
Needs transparency-dev/armored-witness/pull/17 .
=> Add support for firmware logging

Dockerfile
We do not need protoc anymore after https://github.com/transparency-dev/armored-witness-os/pull/56
=> Remove protoc from Dockerfile and update installed dependencies.

release/README.md
Still some work here to do, including more specifics on the WithSecure signing part, moving some of the details from the comments in `cloudbuild_withsecure_signature.yaml` to the README, but wanted to get this page up first.
=> Add high level overview of the release process and Claimant Model for the OS.

.github/workflows/pr_build.yml, Makefile
This PR enables local dev support for signed manifests.
To fit with the two-party scheme we'd already planned for the ELF signatures, this change will cause the manifest file to be signed with both local keys.
=> Sign manifest for local dev

Makefile
This PR should fix the breakage in the CI pipeline.
This target shouldn't attempt to create a manifest as that is done by the pipeline itself in a later stage.
=> trusted_os_release shouldn't create a manifest

Makefile, cmd/proofbundle/main.go, trusted_os/main.go
This PR re-enables the embedded applet feature, useful for development work.
A new tool, `proofbundle`, is added which creates `GOB` encoded proof bundles.
The `go:embed` in the OS is updated to store both the `ELF` binary, and the `proof bundle` file, and performs the same FT verification on the embedded applet as it would when reading from MMC.
The `Makefile` is updated to use the tool to create a valid `proofbundle` for the applet ELF it copies over.
=> Make embedded applets work again

api/rpc/rpc.go, cmd/proofbundle/main.go, go.sum, trusted_os/flash.go, trusted_os/main.go, trusted_os/rpc.go
This PR improves the update flow and fixes some issues:
- Remove all trace of detected signatures as we're now relying on manifest signatures
- Pad short buffers being written to MMC so the last sector will always be written
- Verify the proof bundle for the applet before writing to MMC
=> Improve update RPC flow

Makefile, go.mod, go.sum, release/cloudbuild_ci.yaml
This PR updates the Makefile and cloudbuild configs to store the os firmware binary in the correct CAS location.
See https://github.com/transparency-dev/armored-witness-common/pull/15
=> Store OS firmware binary in CAS

Dockerfile, release/cloudbuild_ci.yaml
This PR makes a number of improvements to the CI build pipeline:
- Uses an incrementing "fake" tag for builds, so that witness devices can track updates from the log
- Fixes incorrect key hashes
- Small speed up from reducing logging volume
=> Improve os CI build pipeline

release/cloudbuild_ci.yaml
This PR causes the CI build pipeline to mimic the cosigned manifest by re-signing with a 2nd CI key.
This results in the following manifest being logged:
```
{
"component": "TRUSTED_OS",
"git_tag_name": "0.2.1698942116-incompatible",
"git_commit_fingerprint": "c02bdf04933732008666a1dacdd94bba6a46c3d6",
"firmware_digest_sha256": "ei2riddWYDRVUN1WwVUoVY+7uMNIU30Yo8NL2A4ymRQ=",
"tamago_version": "1.20.6"
}
— transparency.dev-aw-os1-ci eg6u8zcOAHk0RSyqiq8OYq/XY61W9zNUnTyfEx8bvDZRAIvRahFqu96ZiKTOG66EIPdzZdEN0YnO8QEUsxYBrcmyQAw=
— transparency.dev-aw-os2-ci r45BFF/shXfHJoM0/boGKKDbAlEbfTQLUJ8S6fkXuu3vqNPlRrg8wcs7WJQdsZsF1aPuUvnF1mXkEmj4Sa/bdG3N3Qc=
```
=> Countersign CI manifest

.github/workflows/pr_build.yml, Makefile, release/cloudbuild_ci.yaml
This PR bumps the version of TamaGo used to build and test to `1.21.3` (required due to recent changes to support `BEE`), and adds a check to the `Makefile` to ensure that a `TamaGo` version at least this new is always used to compile binaries.
=> Bump to TamaGo v1.21.3

Makefile, api/api.go, trusted_os/main.go
This information isn't useful and makes it hard to reproducibly build the same output. If it was still useful then we could add it to the manifest, but it isn't, and so it is being removed. Removing this from the APIs here would be a backwards incompatible change, so the Build still exists in code, but as an empty string constant.
=> Don't embed build info

release/cloudbuild_ci.yaml
This fixes the problem that objects uploaded to `entriesDir` are not deleted.
Same PR, but for the applet: https://github.com/transparency-dev/armored-witness-applet/pull/186
=> Use per Cloud Build trigger unique entriesDir for sequencing.

api/rpc/rpc.go, trusted_os/rpc.go
This PR allows the applet to break up firmware-update requests to the OS into multiple, smaller, chunks.
Occasionally we've observed an OOM situation in the OS when trying to do a firmware update, this is usually after the device has been running for some time.
I suspect this is due to a combination of memory becoming fragmented over time, and the fact that, internally, the RPC mechanism is built using Go's [jsonrpc](https://pkg.go.dev/net/rpc/jsonrpc) so the already large firmware blobs are being further expanded by Base64 encoding.
=> Add support for chunked firmware updates

trusted_os/flash.go, trusted_os/main.go
This PR attempts to increase device resilience in the face of update failures by adding support for an A/B firmware scheme for both the OS and Applet firmware images.
At boot time, the device figures out which of the A/B slots were used to load the OS/Applet from, and then uses this information when auto-updating to write newer firmware to the _other_ slot. If there was an error during update, the previously booted firmware should remain intact and will be used when the device reboots/is rebooted.
This isn't 100% watertight due to how the config gets updated, but significantly reduces the window during which an power failure/crash/etc. can cause the device firmware to become corrupt (from ~20MB of writes down to ~1KB).
Changes are contained here - no updates to support this are necessary …
=> Add support for A/B partitions for OS and Applet firmware

.github/workflows/pr_build.yml, Makefile, go.mod, go.sum, release/cloudbuild_ci.yaml, release/cloudbuild_presubmit.yaml
There are some important TamaGo fixes in 1.21.5, this PR makes that the minimum version.
See also:
- transparency-dev/armored-witness-applet/pull/200
- transparency-dev/armored-witness-boot/pull/57
=> Bump TamaGo-go version to 1.21.5 for OS

Makefile, trusted_os/flash.go, trusted_os/main.go
This PR adds the requirement that OS updates must also pass FT verification, bringing this path into line with the existing check during Applet updates.
(@mhutchinson in case these changes affect the [reproducible build verifier](https://github.com/transparency-dev/armored-witness/tree/main/verifier/build) in any way).
=> OS update verifies FT bundle

release/cloudbuild_ci.yaml
This was downgraded from 0.2.X to 0.0.X because it seemed arbitrary. This caused a latent problem that has now come to light as we're trying to flash these CI builds onto the devices, which is that recent builds appear older than those from before the version downgrade. In the interests of being pragmatic, bumping this version to a newer version bypasses this problem. We can reset this to 0.0.X again should we ever rotate the CI logs.
=> Bump CI version to 0.3.X

Makefile, rpmb/op.go, trusted_os/main.go, trusted_os/rpmb.go, trusted_os/rpmb_fake.go, trusted_os/storage.go, trusted_os/storage_debug.go
Add an implementation of fake RPMB storage so that we can keep a counter for the witness identity in case the device needs to be wiped and a new identity needs to be doled out. This counter will be used in deriving the witness key in the applet.
Tried to write some testing, but even moving `trusted_os/rpmb*` stuff out of package `main` still requires Tamago, because the real rpmb implementation imports Tamago.
=> Add fake RPMB.

Dockerfile, trusted_os/ctl.go, trusted_os/flash.go, trusted_os/rpc.go, trusted_os/rpmb.go, trusted_os/rpmb_fake.go
Reverts transparency-dev/armored-witness-os#142
=> Revert "Allow passing the witness identity counter to the Trusted Applet."

release/cloudbuild_ci.yaml
Any of these values could be rotated in the future, and given they are critical for reproducible builds they should be in the manifest. One could argue that these should have their own top-level named entry in the manifest rather than being buried in build_envs. For pragmatism, let's use this approach for now and we can revisit this in a month as part of a whole manifest refactor before we commit to v1.
=> Commit to all build envs in manifest

trusted_os/rpmb.go
```
00:00:03 RPMB program key flag already fused
00:00:03 SM firmware rollback check failure, EOF
```
=> Handle case where no rollback version was yet stored

trusted_os/debug.go
This PR stubs out the forensics in debug builds.
Removing this for the moment as it sometimes causes the device to get stuck while trying to emit the stack.
=> Stop forensics from running for now

trusted_os/debug.go, trusted_os/main.go
Temporarily cause the applet to hang if it crashes, rather than attempt a restart, to enable us to catch a rare event.
=> DEV: Hang on applet exit

go.mod, go.sum
To pull in usbarmory/tamago#44
=> Bump tamago to 3bf2d607eccb28f9093c043625226ede642609b7

trusted_os/rpc.go
Perform the Applet version rollback check, but only on fused, real, h/w.
=> Re-enable applet version rollback check

trusted_os/ctl.go, trusted_os/main.go
The PR ensures that the built-in GitTag is parseable by the semver package.
=> Fix OS handling of version string

.github/workflows/pr_build.yml, Makefile, go.mod
This PR bumps the minimum version of Tamago to 1.22.4 in prep for #256.
Needs transparency-dev/armored-witness#264 for presubmit.
=> Bump Tamago to 1.22.4

trusted_os/rpc.go
handler.G and handler.P should be validated to prevent an abusive applet piercing OS memory
=> validate applet handler pointers

trusted_os/handler.go, trusted_os/handler.s
This PR adds support for applets built with tamago < 1.23 by making available the previous version of runtime·WakeG.
=> add support to wake tamago < 1.23 applets on >= 1.23 os

trusted_os/handler.go, trusted_os/main.go
This PR allows the OS to inspect the version of TamaGo used to compile the applet, and select the appropriate mechanism for waking that runtime when necessary.
Boot log showing a 1.23 SM/OS launching a 1.22.4 Applet, using "legacy wake handler", and successfully receiving network packets:
```
00:00:03 tamago/arm (go1.23.1) • TEE security monitor (Secure World system/monitor) • b0a0fc8
00:00:03 Loaded OS from slot B
00:00:03 SM log verification pub: DEV-FT-LOG+22ab00a9+Ab6KRXXm5Hs9YuJWpNNlvlZ4BAisHRx7TR1375f7n5VZ
00:00:03 SM applet verification pub: DEV-APPLET+79441a79+Af/Q6S4XZtrNchMilwJK+YI3HAxE+0YqMMSznbOHdHXA
00:00:03 Loaded applet from slot A
00:00:03 SM Verifying applet bundle
00:00:06 SM Loaded applet version 0.2.1-24-ge90a715 (with TamaGo runtime 1.22.4)
00:00:06 SM Using legacy …
```
=> OS uses appropriate wakeHandler for applet runtime

trusted_os/handler.go, trusted_os/handler.s
This PR adds support for the monitor (when built with `tamago1.24`) to detect and correctly wake applets built with `tamago1.23` and `tamago1.24`.
Tested OS `tamago1.24`, Applet `tamago1.23`:
```
armored-witness-boot • tamago/arm (go1.23.1) • 3eefc3c • i.MX6UL
armored-witness-boot: version 0.1.0-35-g3eefc3c
armored-witness-boot: loading configuration & kernel at USDHC2@10485760
armored-witness-boot: log verifier: DEV-FT-LOG+22ab00a9+Ab6KRXXm5Hs9YuJWpNNlvlZ4BAisHRx7TR1375f7n5VZ
armored-witness-boot: kernel verifier: DEV-OS-1+23597896+AYFiM0rc8J6/64lwD85JQbNmE79dl0N8GBPRTZqT+VMe
armored-witness-boot: kernel verifier: DEV-OS-2+05022ebf+AcjbNE2bka89SEvmmgfAYZBA45cadsGUqUr7wh3XTdNx
armored-witness-boot: loaded kernel version 0.4.54
armored-witness-boot: verified kernel …
```
=> Add wake handler support for go1.23 and go1.24
